[project]
name = "mtga-app"
version = "0.1.0"
description = "MTGA Tauri Python backend"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytauri==0.8.*",
    "pytauri-wheel==0.8.*",
    "cryptography>=45.0.0",
    "flask",
    "requests",
    "httpx>=0.28.1",
    "platformdirs>=4.3.0",
    "PyYAML",
    "xxhash>=3.5.0",
]

[build-system]
requires = ["setuptools>=80"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = false

[tool.setuptools.packages.find]
where = ["."]
include = ["mtga_app*", "modules*"]
exclude = ["build*", "target*", "pyembed*"]
namespaces = false

[tool.setuptools.package-data]
modules = ["resources/ca/**", "resources/trae/**", "trae_patch/macos/*.json"]

[dependency-groups]
dev = [
    "aiohttp>=3.13.3",
    "pyright>=1.1.408",
    "ruff>=0.14.4",
    "yamllint>=1.37.1",
]

[tool.pyright]
typeCheckingMode = "strict"
reportMissingTypeStubs = false
pythonVersion = "3.13"
venvPath = "."
venv = ".venv"
extraPaths = ["."]
exclude = [
    ".uv_cache",
    "**/node_modules",
    "**/__pycache__",
    # 👇 necessary, because when `tauri-cli bundles python,
    # it will copy `pyembed` to the target directory (i.e., rust output dir).
    "**/target",
    # 👆
    "**/dist",
    "**/.venv",
    "**/.*",
    "**/build",
    "**/mtga_app.egg-info",
    "**/pyembed"
]

[tool.ruff]
line-length = 100
target-version = "py313"

# Включены основные наборы правил: E/F — базовые ошибки; I=imports; B=bugbear; UP=pyupgrade; SIM=упрощение;
# PL = подмножество правил Pylint (уменьшает зависимость от Pylint)
[tool.ruff.lint]
select  = ["E", "F", "I", "B", "UP", "SIM", "PL"]
fixable = ["ALL"]  # Автоисправление где возможно

[tool.ruff.format]
line-ending = "auto"
